<a href="https://colab.research.google.com/github/thanvika05/Thanvika_CodeBooster_2026/blob/main/Day2/Day_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import sqlite3
import pandas as pd
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

print("All libraries imported successfully")
print(f"pandas version: {pd.__version__}")
print(f"sqlite3 version: {sqlite3.sqlite_version}")

All libraries imported successfully
pandas version: 2.2.2
sqlite3 version: 3.37.2

In [5]:
df = pd.read_csv('student_performance.csv')
print(f"Dataset loaded: {df.shape[0]} students, {df.shape}")

Dataset loaded: 30 students, (30, 13)

In [8]:
selected_columns_df = df[['student_id', 'name', 'department', 'math_score']]
display(selected_columns_df.head())

   student_id          name        department  math_score
0        1001  Aarav Sharma  Computer Science          85
1        1002   Priya Patel  Computer Science          76
2        1003   Rohit Verma       Electronics          65
3        1004   Sneha Reddy        Mechanical          70
4        1005    Arjun Nair  Computer Science          92

In [9]:
conn = sqlite3.connect(':memory:')
selected_columns_df.to_sql('students', conn, index=False, if_exists='replace')

30

In [10]:
sql_query = "SELECT student_id, name, department, math_score FROM students"
sql_result_df = pd.read_sql_query(sql_query, conn)
display(sql_result_df.head())

   student_id          name        department  math_score
0        1001  Aarav Sharma  Computer Science          85
1        1002   Priya Patel  Computer Science          76
2        1003   Rohit Verma       Electronics          65
3        1004   Sneha Reddy        Mechanical          70
4        1005    Arjun Nair  Computer Science          92

In [15]:
conn = sqlite3.connect('internship.db')
# Write the df DataFrame to a SQL table named 'students' in internship.db
df.to_sql('students', conn, index=False, if_exists='replace')

cursor = conn.cursor()

query = "SELECT student_id , name , age FROM students LIMIT 10"
data = pd.read_sql(query,conn)
print("=== DataBase Connected Successfully ===")
print(data)
conn.close()

=== DataBase Connected Successfully ===
   student_id          name  age
0        1001  Aarav Sharma   19
1        1002   Priya Patel   20
2        1003   Rohit Verma   19
3        1004   Sneha Reddy   20
4        1005    Arjun Nair   19
5        1006   Meera Joshi   20
6        1007   Kiran Kumar   21
7        1008   Divya Singh   19
8        1009  Rahul Mishra   20
9        1010    Ananya Das   19

In [19]:
conn = sqlite3.connect('internship.db')
query_top_scorers = "SELECT name,department,math_score FROM students ORDER BY math_score DESC LIMIT 5"
top_scorers_df = pd.read_sql(query_top_scorers, conn)
print("Top 5 Math Scorers:")
print(top_scorers_df)
conn.close()

Top 5 Math Scorers:
             name        department  math_score
0      Ananya Das  Computer Science          95
1     Tanvi Mehta  Computer Science          93
2      Arjun Nair  Computer Science          92
3  Akanksha Yadav  Computer Science          91
4  Swati Kulkarni  Computer Science          90

In [23]:
conn = sqlite3.connect('internship.db')
query_cs_students = "SELECT name, math_score, science_score, programming_score, attendance_percentage FROM students WHERE department = 'Computer Science' ORDER BY math_score DESC"
cs_students_df = pd.read_sql(query_cs_students, conn)
print("Computer Science Students' Performance (Ordered by Math Score Descending):")
print(cs_students_df)
conn.close()

Computer Science Students' Performance (Ordered by Math Score Descending):
              name  math_score  science_score  programming_score  \
0       Ananya Das          95             89                 97
1      Tanvi Mehta          93             90                 96
2       Arjun Nair          92             88                 95
3   Akanksha Yadav          91             93                 94
4   Swati Kulkarni          90             87                 92
5      Divya Singh          88             91                 93
6        Amit Bose          86             82                 89
7     Aarav Sharma          85             78                 91
8    Gaurav Shukla          84             79                 87
9       Suresh Rao          83             86                 88
10    Nisha Kapoor          79             84                 83
11     Priya Patel          76             82                 79
12     Ajay Tiwari          71             69                 76

    attendance_percentage
0                      98
1                      97
2                      90
3                      95
4                      94
5                      96
6                      91
7                      92
8                      87
9                      88
10                     89
11                     87
12                     75

In [25]:
conn = sqlite3.connect('internship.db')
query_high_attendance = "SELECT name, department, attendance_percentage FROM students WHERE attendance_percentage > 90 AND department != 'Civil' ORDER BY attendance_percentage DESC"
high_attendance_df = pd.read_sql(query_high_attendance, conn)
print("Students with high attendance (above 90%) excluding Civil department:")
print(high_attendance_df)
conn.close()

Students with high attendance (above 90%) excluding Civil department:
             name        department  attendance_percentage
0      Ananya Das  Computer Science                     98
1     Tanvi Mehta  Computer Science                     97
2     Divya Singh  Computer Science                     96
3     Sneha Reddy        Mechanical                     95
4  Akanksha Yadav  Computer Science                     95
5  Swati Kulkarni  Computer Science                     94
6    Ritu Agarwal       Electronics                     93
7    Aarav Sharma  Computer Science                     92
8   Kavya Nambiar        Mechanical                     91
9       Amit Bose  Computer Science                     91

In [29]:
conn = sqlite3.connect('internship.db')
query_high_attendance = "SELECT name, department, attendance_percentage FROM students WHERE attendance_percentage > 93 AND department NOT IN ('Mechanical') ORDER BY attendance_percentage DESC"
high_attendance_df = pd.read_sql(query_high_attendance, conn)
print("Students with high attendance (above 90%) excluding Mechanical departments:")
print(high_attendance_df)
conn.close()

Students with high attendance (above 90%) excluding Mechanical departments:
             name        department  attendance_percentage
0      Ananya Das  Computer Science                     98
1     Tanvi Mehta  Computer Science                     97
2     Divya Singh  Computer Science                     96
3  Akanksha Yadav  Computer Science                     95
4  Swati Kulkarni  Computer Science                     94

In [30]:
conn = sqlite3.connect('internship.db')
query_name_range = "SELECT name, department, math_score FROM students WHERE name BETWEEN 'A' AND 'G' ORDER BY name ASC"
students_a_to_f_df = pd.read_sql(query_name_range, conn)
print("Students with names starting from A to F:")
print(students_a_to_f_df)
conn.close()

Students with names starting from A to F:
             name        department  math_score
0    Aarav Sharma  Computer Science          85
1     Ajay Tiwari  Computer Science          71
2  Akanksha Yadav  Computer Science          91
3       Amit Bose  Computer Science          86
4      Ananya Das  Computer Science          95
5      Arjun Nair  Computer Science          92
6  Deepak Chauhan        Mechanical          68
7     Divya Singh  Computer Science          88